package com.kohler.constants;

public class CategoryPathSQL {
    public static final String GET_PATH        = "select CM.CATEGORY_METADATA_ID,CM.PARENT_ID,PF.PUBLISH_FOLDER_PATH AS PC_PATH,"
            + "PF1.PUBLISH_FOLDER_PATH AS MOBILE_PATH, TT.GENERATE_URL AS PC_FOLDER_PATH,TT1.GENERATE_URL AS MOBILE_FOLDER_PATH "
            + "from CATEGORY_METADATA CM "
            + "left join CATEGORY  CC on CC.CATEGORY_METADATA_ID = CM.CATEGORY_METADATA_ID "
            + "left join TEMPLATE TT on CC.PC_TEMPLATE_ID = TT.TEMPLATE_ID left join PUBLISH_FOLDER PF on TT.PUBLISH_FOLDER_ID = PF.PUBLISH_FOLDER_ID "
            + "left join TEMPLATE TT1 on CC.MOBILE_TEMPLATE_ID = TT1.TEMPLATE_ID "
            + "left join PUBLISH_FOLDER PF1 on TT1.PUBLISH_FOLDER_ID = PF1.PUBLISH_FOLDER_ID "
            + "where CC.CATEGORY_ID = ?";

    public static final String GET_FOLDER_PATH = "select * from PRODUCT PP left join PRODUCT_METADATA PM ON PP.PRODUCT_METADATA_ID=PM.PRODUCT_METADATA_ID where PP.PRODUCT_ID = ?";
}
