/**
 * Copyright (C) 2000-2006 
Kohler Company. All Rights \
Reserved.
 */
package com.kohler.constants;

/**
 * Product SQL
 *
 * @author WHH
 * @Date 2014年10月28日
 */
public class ProductSolrSQL {

    public static final String SELECT_BY_ID = "select PRODUCT_ID,LANG,PPM.PRODUCT_METADATA_ID,PC_TEMPLATE_ID,MOBILE_TEMPLATE_ID,"
            + "COMBINE_PRODUCT_METADATA_ID, CATEGORY_METADATA_ID,SEQ_NO,COLLECTION_METADATA_ID,COLLECTION_STYLE_METADATA_ID,"
            + "DATA_TEMPLATE_ID, PRODUCT_NAME,SEO_TITLE_PC,SEO_KEYWORDS_PC,SEO_DESCRIPTION_PC,SEO_H1TAG_PC,SEO_TITLE_MOBILE, "
            + "SEO_KEYWORDS_MOBILE,SEO_DESCRIPTION_MOBILE,SEO_H1TAG_MOBILE,PRODUCT_CODE,PUBLISH_DATE,PUBLISH_DATE AS MODITY_TIME "
            + "from PRODUCT PPM "
            + "left join PRODUCT_METADATA PM ON PPM.PRODUCT_METADATA_ID=PM.PRODUCT_METADATA_ID "
            + "where PPM.PRODUCT_ID = ?";
    
}
