package com.kohler.constants;

public class VwSolrSkuSQL {
    public static final String GET_PATH        = "select CM.CATEGORY_METADATA_ID,CM.PARENT_ID,PF.PUBLISH_FOLDER_PATH AS PC_PATH,"
            + "PF1.PUBLISH_FOLDER_PATH AS MOBILE_PATH, TT.GENERATE_URL AS PC_FOLDER_PATH,TT1.GENERATE_URL AS MOBILE_FOLDER_PATH "
            + "from CATEGORY_METADATA CM "
            + "left join CATEGORY  CC on CC.CATEGORY_METADATA_ID = CM.CATEGORY_METADATA_ID "
            + "left join TEMPLATE TT on CC.PC_TEMPLATE_ID = TT.TEMPLATE_ID left join PUBLISH_FOLDER PF on TT.PUBLISH_FOLDER_ID = PF.PUBLISH_FOLDER_ID "
            + "left join TEMPLATE TT1 on CC.MOBILE_TEMPLATE_ID = TT1.TEMPLATE_ID "
            + "left join PUBLISH_FOLDER PF1 on TT1.PUBLISH_FOLDER_ID = PF1.PUBLISH_FOLDER_ID "
            + "where CC.CATEGORY_ID = ?";

    public static final String GET_FOLDER_PATH = "select * from PRODUCT PP left join PRODUCT_METADATA PM ON PP.PRODUCT_METADATA_ID=PM.PRODUCT_METADATA_ID where PP.PRODUCT_ID = ?";
    
    public static final String GET_ALL = "select SKU_ID,LANG,SKU_METADATA_ID,SKU_CODE,SKU_NAME,IS_DEFAULT,SKU_PRICE,PRODUCT_METADATA_ID,"
            + "PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,SUB_CATEGORY_METADATA_ID,SUB_CATEGORY_ID,SUB_CATEGORY_NAME,CATEGORY_METADATA_ID,CATEGORY_ID,"
            + "CATEGORY_NAME,SECTION_METADATA_ID,SECTION_NAME,IMAGE_SOURCE,LIST_IMAGE_URL,LIST_IMAGE_ID,LIST_IMAGE_ALT,DETAIL_IMAGE1_URL,DETAIL_IMAGE1_ID,"
            + "DETAIL_IMAGE1_ALT,COLLECTION_NAME,now() as MODIFY_TIME "
            + "from VW_SOLR_SKU ";
    
    public static final String GET_BY_TIME = "select SKU_ID,LANG,SKU_METADATA_ID,SKU_CODE,SKU_NAME,IS_DEFAULT,SKU_PRICE,PRODUCT_METADATA_ID,"
            + "PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,SUB_CATEGORY_METADATA_ID,SUB_CATEGORY_ID,SUB_CATEGORY_NAME,CATEGORY_METADATA_ID,CATEGORY_ID,"
            + "CATEGORY_NAME,SECTION_METADATA_ID,SECTION_NAME,IMAGE_SOURCE,LIST_IMAGE_URL,LIST_IMAGE_ID,LIST_IMAGE_ALT,DETAIL_IMAGE1_URL,DETAIL_IMAGE1_ID,"
            + "DETAIL_IMAGE1_ALT,COLLECTION_NAME,now() as MODIFY_TIME "
            + "from VW_SOLR_SKU "
            + "where MODIFY_TIME > ? and MODIFY_TIME < now()";
}
